import './globals.css'
import type { Metadata } from 'next'

import { Rubik } from 'next/font/google'
const rubik = Rubik({ subsets: ['latin'] })

//components
import Navbar from './components/Navbar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
   
    <html lang="en" style={{backgroundColor: 'darkslategrey'}}>
     
      <body className={rubik.className} >
        <Navbar />
       
 
        {children}</body>
    </html>
 
  )
}
